// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        public static Valve.VR.SteamVR_Input_ActionSet_default _default;
        
        public static Valve.VR.SteamVR_Input_ActionSet_rock rock;
        
        public static Valve.VR.SteamVR_Input_ActionSet_buggybuddy buggybuddy;
        
        public static Valve.VR.SteamVR_Input_ActionSet_space space;
        
        public static Valve.VR.SteamVR_Input_ActionSet_grenade grenade;
        
        public static Valve.VR.SteamVR_Input_ActionSet_squeezable squeezable;
        
        public static Valve.VR.SteamVR_Input_ActionSet_teleporting teleporting;
        
        public static Valve.VR.SteamVR_Input_ActionSet_gun gun;
        
        public static void Dynamic_InitializeActionSets()
        {
            SteamVR_Input._default.Initialize();
            SteamVR_Input.rock.Initialize();
            SteamVR_Input.buggybuddy.Initialize();
            SteamVR_Input.space.Initialize();
            SteamVR_Input.grenade.Initialize();
            SteamVR_Input.squeezable.Initialize();
            SteamVR_Input.teleporting.Initialize();
            SteamVR_Input.gun.Initialize();
        }
        
        public static void Dynamic_InitializeInstanceActionSets()
        {
            Valve.VR.SteamVR_Input._default = ((SteamVR_Input_ActionSet_default)(SteamVR_Input_References.GetActionSet("_default")));
            Valve.VR.SteamVR_Input.rock = ((SteamVR_Input_ActionSet_rock)(SteamVR_Input_References.GetActionSet("rock")));
            Valve.VR.SteamVR_Input.buggybuddy = ((SteamVR_Input_ActionSet_buggybuddy)(SteamVR_Input_References.GetActionSet("buggybuddy")));
            Valve.VR.SteamVR_Input.space = ((SteamVR_Input_ActionSet_space)(SteamVR_Input_References.GetActionSet("space")));
            Valve.VR.SteamVR_Input.grenade = ((SteamVR_Input_ActionSet_grenade)(SteamVR_Input_References.GetActionSet("grenade")));
            Valve.VR.SteamVR_Input.squeezable = ((SteamVR_Input_ActionSet_squeezable)(SteamVR_Input_References.GetActionSet("squeezable")));
            Valve.VR.SteamVR_Input.teleporting = ((SteamVR_Input_ActionSet_teleporting)(SteamVR_Input_References.GetActionSet("teleporting")));
            Valve.VR.SteamVR_Input.gun = ((SteamVR_Input_ActionSet_gun)(SteamVR_Input_References.GetActionSet("gun")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[]
            {
                    Valve.VR.SteamVR_Input._default,
                    Valve.VR.SteamVR_Input.rock,
                    Valve.VR.SteamVR_Input.buggybuddy,
                    Valve.VR.SteamVR_Input.space,
                    Valve.VR.SteamVR_Input.grenade,
                    Valve.VR.SteamVR_Input.squeezable,
                    Valve.VR.SteamVR_Input.teleporting,
                    Valve.VR.SteamVR_Input.gun};
        }
    }
}
