// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_rock p_rock;
        
        private static SteamVR_Input_ActionSet_buggybuddy p_buggybuddy;
        
        private static SteamVR_Input_ActionSet_space p_space;
        
        private static SteamVR_Input_ActionSet_grenade p_grenade;
        
        private static SteamVR_Input_ActionSet_squeezable p_squeezable;
        
        private static SteamVR_Input_ActionSet_teleporting p_teleporting;
        
        private static SteamVR_Input_ActionSet_gun p_gun;
        
        private static SteamVR_Input_ActionSet_raw p_raw;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy <SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_rock rock
        {
            get
            {
                return SteamVR_Actions.p_rock.GetCopy <SteamVR_Input_ActionSet_rock>();
            }
        }
        
        public static SteamVR_Input_ActionSet_buggybuddy buggybuddy
        {
            get
            {
                return SteamVR_Actions.p_buggybuddy.GetCopy <SteamVR_Input_ActionSet_buggybuddy>();
            }
        }
        
        public static SteamVR_Input_ActionSet_space space
        {
            get
            {
                return SteamVR_Actions.p_space.GetCopy <SteamVR_Input_ActionSet_space>();
            }
        }
        
        public static SteamVR_Input_ActionSet_grenade grenade
        {
            get
            {
                return SteamVR_Actions.p_grenade.GetCopy <SteamVR_Input_ActionSet_grenade>();
            }
        }
        
        public static SteamVR_Input_ActionSet_squeezable squeezable
        {
            get
            {
                return SteamVR_Actions.p_squeezable.GetCopy <SteamVR_Input_ActionSet_squeezable>();
            }
        }
        
        public static SteamVR_Input_ActionSet_teleporting teleporting
        {
            get
            {
                return SteamVR_Actions.p_teleporting.GetCopy <SteamVR_Input_ActionSet_teleporting>();
            }
        }
        
        public static SteamVR_Input_ActionSet_gun gun
        {
            get
            {
                return SteamVR_Actions.p_gun.GetCopy <SteamVR_Input_ActionSet_gun>();
            }
        }
        
        public static SteamVR_Input_ActionSet_raw raw
        {
            get
            {
                return SteamVR_Actions.p_raw.GetCopy <SteamVR_Input_ActionSet_raw>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_rock = ((SteamVR_Input_ActionSet_rock)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_rock>("/actions/rock")));
            SteamVR_Actions.p_buggybuddy = ((SteamVR_Input_ActionSet_buggybuddy)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_buggybuddy>("/actions/buggybuddy")));
            SteamVR_Actions.p_space = ((SteamVR_Input_ActionSet_space)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_space>("/actions/space")));
            SteamVR_Actions.p_grenade = ((SteamVR_Input_ActionSet_grenade)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_grenade>("/actions/grenade")));
            SteamVR_Actions.p_squeezable = ((SteamVR_Input_ActionSet_squeezable)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_squeezable>("/actions/squeezable")));
            SteamVR_Actions.p_teleporting = ((SteamVR_Input_ActionSet_teleporting)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_teleporting>("/actions/teleporting")));
            SteamVR_Actions.p_gun = ((SteamVR_Input_ActionSet_gun)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_gun>("/actions/gun")));
            SteamVR_Actions.p_raw = ((SteamVR_Input_ActionSet_raw)(SteamVR_ActionSet.Create <SteamVR_Input_ActionSet_raw>("/actions/raw")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[]
            {
                    SteamVR_Actions._default,
                    SteamVR_Actions.rock,
                    SteamVR_Actions.buggybuddy,
                    SteamVR_Actions.space,
                    SteamVR_Actions.grenade,
                    SteamVR_Actions.squeezable,
                    SteamVR_Actions.teleporting,
                    SteamVR_Actions.gun,
                    SteamVR_Actions.raw};
        }
    }
}
