// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        public static SteamVR_Action_Boolean __actions_default_in_GrabPinch;
        
        public static SteamVR_Action_Boolean __actions_default_in_GrabGrip;
        
        public static SteamVR_Action_Pose __actions_default_in_Pose;
        
        public static SteamVR_Action_Skeleton __actions_default_in_SkeletonLeftHand;
        
        public static SteamVR_Action_Skeleton __actions_default_in_SkeletonRightHand;
        
        public static SteamVR_Action_Vibration __actions_default_out_Haptic;
        
        public static SteamVR_Action_Single __actions_rock_in_Squeeze;
        
        public static SteamVR_Action_Boolean __actions_rock_in_Crush;
        
        public static SteamVR_Action_Single __actions_buggybuddy_in_Throttle;
        
        public static SteamVR_Action_Vector2 __actions_buggybuddy_in_Steer;
        
        public static SteamVR_Action_Boolean __actions_buggybuddy_in_Brake;
        
        public static SteamVR_Action_Boolean __actions_buggybuddy_in_Reset;
        
        public static SteamVR_Action_Boolean __actions_buggybuddy_in_Turbo;
        
        public static SteamVR_Action_Boolean __actions_space_in_DeleterSelect;
        
        public static SteamVR_Action_Boolean __actions_space_in_DeleterDelete;
        
        public static SteamVR_Action_Boolean __actions_grenade_in_PrimeGrenade;
        
        public static SteamVR_Action_Single __actions_squeezable_in_SqueezePinch;
        
        public static SteamVR_Action_Single __actions_squeezable_in_SqueezeGrip;
        
        public static SteamVR_Action_Boolean __actions_teleporting_in_Teleport;
        
        public static SteamVR_Action_Boolean __actions_gun_in_Fire;
        
        public static void Dynamic_InitializeActions()
        {
            SteamVR_Input.__actions_default_in_GrabPinch.Initialize();
            SteamVR_Input.__actions_default_in_GrabGrip.Initialize();
            SteamVR_Input.__actions_default_in_Pose.Initialize();
            SteamVR_Input.__actions_default_in_SkeletonLeftHand.Initialize();
            SteamVR_Input.__actions_default_in_SkeletonRightHand.Initialize();
            SteamVR_Input.__actions_default_out_Haptic.Initialize();
            SteamVR_Input.__actions_rock_in_Squeeze.Initialize();
            SteamVR_Input.__actions_rock_in_Crush.Initialize();
            SteamVR_Input.__actions_buggybuddy_in_Throttle.Initialize();
            SteamVR_Input.__actions_buggybuddy_in_Steer.Initialize();
            SteamVR_Input.__actions_buggybuddy_in_Brake.Initialize();
            SteamVR_Input.__actions_buggybuddy_in_Reset.Initialize();
            SteamVR_Input.__actions_buggybuddy_in_Turbo.Initialize();
            SteamVR_Input.__actions_space_in_DeleterSelect.Initialize();
            SteamVR_Input.__actions_space_in_DeleterDelete.Initialize();
            SteamVR_Input.__actions_grenade_in_PrimeGrenade.Initialize();
            SteamVR_Input.__actions_squeezable_in_SqueezePinch.Initialize();
            SteamVR_Input.__actions_squeezable_in_SqueezeGrip.Initialize();
            SteamVR_Input.__actions_teleporting_in_Teleport.Initialize();
            SteamVR_Input.__actions_gun_in_Fire.Initialize();
        }
        
        public static void Dynamic_InitializeInstanceActions()
        {
            Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GrabPinch")));
            Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GrabGrip")));
            Valve.VR.SteamVR_Input.__actions_default_in_Pose = ((SteamVR_Action_Pose)(SteamVR_Input_References.GetAction("__actions_default_in_Pose")));
            Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonLeftHand")));
            Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonRightHand")));
            Valve.VR.SteamVR_Input.__actions_default_out_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Input_References.GetAction("__actions_default_out_Haptic")));
            Valve.VR.SteamVR_Input.__actions_rock_in_Squeeze = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_rock_in_Squeeze")));
            Valve.VR.SteamVR_Input.__actions_rock_in_Crush = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_rock_in_Crush")));
            Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Throttle = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_buggybuddy_in_Throttle")));
            Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Steer = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_buggybuddy_in_Steer")));
            Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Brake = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_buggybuddy_in_Brake")));
            Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Reset = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_buggybuddy_in_Reset")));
            Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Turbo = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_buggybuddy_in_Turbo")));
            Valve.VR.SteamVR_Input.__actions_space_in_DeleterSelect = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_space_in_DeleterSelect")));
            Valve.VR.SteamVR_Input.__actions_space_in_DeleterDelete = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_space_in_DeleterDelete")));
            Valve.VR.SteamVR_Input.__actions_grenade_in_PrimeGrenade = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_grenade_in_PrimeGrenade")));
            Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezePinch = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_squeezable_in_SqueezePinch")));
            Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezeGrip = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_squeezable_in_SqueezeGrip")));
            Valve.VR.SteamVR_Input.__actions_teleporting_in_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_teleporting_in_Teleport")));
            Valve.VR.SteamVR_Input.__actions_gun_in_Fire = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_gun_in_Fire")));
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.__actions_default_out_Haptic,
                    Valve.VR.SteamVR_Input.__actions_rock_in_Squeeze,
                    Valve.VR.SteamVR_Input.__actions_rock_in_Crush,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Steer,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Reset,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Turbo,
                    Valve.VR.SteamVR_Input.__actions_space_in_DeleterSelect,
                    Valve.VR.SteamVR_Input.__actions_space_in_DeleterDelete,
                    Valve.VR.SteamVR_Input.__actions_grenade_in_PrimeGrenade,
                    Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezePinch,
                    Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezeGrip,
                    Valve.VR.SteamVR_Input.__actions_teleporting_in_Teleport,
                    Valve.VR.SteamVR_Input.__actions_gun_in_Fire};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.SteamVR_Action_In[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.__actions_rock_in_Squeeze,
                    Valve.VR.SteamVR_Input.__actions_rock_in_Crush,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Steer,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Reset,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Turbo,
                    Valve.VR.SteamVR_Input.__actions_space_in_DeleterSelect,
                    Valve.VR.SteamVR_Input.__actions_space_in_DeleterDelete,
                    Valve.VR.SteamVR_Input.__actions_grenade_in_PrimeGrenade,
                    Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezePinch,
                    Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezeGrip,
                    Valve.VR.SteamVR_Input.__actions_teleporting_in_Teleport,
                    Valve.VR.SteamVR_Input.__actions_gun_in_Fire};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.SteamVR_Action_Out[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_rock_in_Crush,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Reset,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Turbo,
                    Valve.VR.SteamVR_Input.__actions_space_in_DeleterSelect,
                    Valve.VR.SteamVR_Input.__actions_space_in_DeleterDelete,
                    Valve.VR.SteamVR_Input.__actions_grenade_in_PrimeGrenade,
                    Valve.VR.SteamVR_Input.__actions_teleporting_in_Teleport,
                    Valve.VR.SteamVR_Input.__actions_gun_in_Fire};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[]
            {
                    Valve.VR.SteamVR_Input.__actions_rock_in_Squeeze,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezePinch,
                    Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezeGrip};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[]
            {
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Steer};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.SteamVR_Action_In[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_rock_in_Squeeze,
                    Valve.VR.SteamVR_Input.__actions_rock_in_Crush,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Steer,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Reset,
                    Valve.VR.SteamVR_Input.__actions_buggybuddy_in_Turbo,
                    Valve.VR.SteamVR_Input.__actions_space_in_DeleterSelect,
                    Valve.VR.SteamVR_Input.__actions_space_in_DeleterDelete,
                    Valve.VR.SteamVR_Input.__actions_grenade_in_PrimeGrenade,
                    Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezePinch,
                    Valve.VR.SteamVR_Input.__actions_squeezable_in_SqueezeGrip,
                    Valve.VR.SteamVR_Input.__actions_teleporting_in_Teleport,
                    Valve.VR.SteamVR_Input.__actions_gun_in_Fire};
        }
    }
}
