// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_buggybuddy_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Single Throttle;
        
        public Valve.VR.SteamVR_Action_Vector2 Steer;
        
        public Valve.VR.SteamVR_Action_Boolean Brake;
        
        public Valve.VR.SteamVR_Action_Boolean Reset;
        
        public Valve.VR.SteamVR_Action_Boolean Turbo;
    }
}
