// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_raw : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ATouch
        {
            get
            {
                return SteamVR_Actions.raw_ATouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean APress
        {
            get
            {
                return SteamVR_Actions.raw_APress;
            }
        }
        
        public virtual SteamVR_Action_Boolean BTouch
        {
            get
            {
                return SteamVR_Actions.raw_BTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean BPress
        {
            get
            {
                return SteamVR_Actions.raw_BPress;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadTouch
        {
            get
            {
                return SteamVR_Actions.raw_TouchpadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadPress
        {
            get
            {
                return SteamVR_Actions.raw_TouchpadPress;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadAxis
        {
            get
            {
                return SteamVR_Actions.raw_TouchpadAxis;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbstickTouch
        {
            get
            {
                return SteamVR_Actions.raw_ThumbstickTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbstickPress
        {
            get
            {
                return SteamVR_Actions.raw_ThumbstickPress;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ThumbstickAxis
        {
            get
            {
                return SteamVR_Actions.raw_ThumbstickAxis;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.raw_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerPress
        {
            get
            {
                return SteamVR_Actions.raw_TriggerPress;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerAxis
        {
            get
            {
                return SteamVR_Actions.raw_TriggerAxis;
            }
        }
        
        public virtual SteamVR_Action_Single GripForceAxis
        {
            get
            {
                return SteamVR_Actions.raw_GripForceAxis;
            }
        }
        
        public virtual SteamVR_Action_Single TopForceAxis
        {
            get
            {
                return SteamVR_Actions.raw_TopForceAxis;
            }
        }
    }
}
