// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_space : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean DeleterSelect
        {
            get
            {
                return SteamVR_Actions.space_DeleterSelect;
            }
        }
        
        public virtual SteamVR_Action_Boolean DeleterDelete
        {
            get
            {
                return SteamVR_Actions.space_DeleterDelete;
            }
        }
    }
}
